version: "3.9"

services:
  feeder:
    image: docker-registry.rahti.csc.fi/student480/toyota-task-one:1.0
    environment:
      - MQTT_URL=mqtt-test.rahtiapp.fi
      - MQTT_PORT=433
      - CLIENT_ID=student480
    # networks:
    #   - student480

  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
      - 8883:8883
    # networks:
    #   - student480
    volumes:
      - ./mosquitto/conf/
        # - ./conf:/mosquitto/conf
        # - ./data:/mosquitto/data
        # - ./log:/mosquitto/log
    depends_on:
      - feeder

networks:
  default:
    external:
      name: student480
