apiVersion: apps/v1
kind: Deployment
metadata:
  name: feeder-deployment
  labels:
    app: feeder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feeder
  template:
    metadata:
      labels:
        app: feeder
    spec:
      containers:
        - name: feeder
          image: docker-registry.rahti.csc.fi/student480/toyota-task-one:1.0
          ports:
            - containerPort: 3000
          env:
            - name: MQTT_URL
              valueFrom:
                configMapKeyRef:
                  name: mosquitto-config
                  key: mosquitto-url
            - name: MQTT_PORT
              value: "1883"
            - name: CLIENT_ID
              value: student480
---
apiVersion: v1
kind: Service
metadata:
  name: feeder-service
spec:
  selector:
    app: feeder
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
