apiVersion: extensions/v1beta1

kind: Ingress

metadata:
  name: mosquitto-service

spec:
  rules:
    - host: mqtt.student480.rahtiapp.fi

      http:
        paths:
          - path: /

            backend:
              serviceName: mosquitto-service
              servicePort: 1883
