apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
data:
  mosquitto.conf: |
    log_type all
    listener 1883
    listener 8883
    allow_anonymous true
    cafile /cert/ca.crt
    certfile /cert/server.crt
    keyfile /cert/server.key
