apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
data:
  mosquitto.conf: |-
    listener 8883
    port 1883
    allow_anonymous true

---
apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-secret
type: Opaque
data:
  secret.file: |
    RGF2aWQgT2NoaWEgc29mdCBkZWZpbmUgcHJvZHVjdCBjb3Vyc2U=

#  cafile conf/ca.crt
#  certfile conf/server.crt
#  keyfile conf/server.key
