apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
data:
  mosquitto.conf: |-
    listener 8883
    listener 1883
    allow_anonymous true
    cafile /cert/ca.crt
    certfile /cert/server.crt
    keyfile /cert/server.key
---
apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-secret
type: Opaque
data:
  secret.file: |
    RGF2aWQgT2NoaWEgc29mdCBkZWZpbmUgcHJvZHVjdCBjb3Vyc2U=
