apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-red
  name: node-red-service
spec:
  ports:
    - name: node-red
      port: 1880
      targetPort: 1880
  selector:
    app: node-red
  sessionAffinity: None
  type: LoadBalancer
